# Generated by Django 5.1.3 on 2024-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectos', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('nombre_integrante', models.CharField(max_length=200)),
                ('fec_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
